name: Checks
description: Run all the necessary checks: lint, types, unit tests
runs:
  using: composite
  steps:
    - name: 🧹 Run lint
      run: yarn lint

    - name: 🧹 Run type check
      run: yarn tsc

    - name: 🧪 Run tests
      run: yarn test
