name: Checks Action
description: Run sanity checks
runs:
  using: composite
  steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test

    - name: Run linter
      run: yarn lint

    - name: Run TypeScript compiler
      run: yarn tsc
